version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: ini
    versions:
    - 1.3.8
